### ISSUE TITLE
No experiments in GitHub

### ISSUE THREAD

**Issue by rishi11** [animeshjain9/CS5610-jainani#1]
HI,

I cannot find your experiments in GitHub. No experiments folder in your website.

**Comment by animeshjain9** [comment]
Hi Rishi,

I have made the experiments folder under the Story folder. Please let me know if you won't find them.

Regards,
Animesh Jain

----- Original Message -----

**Comment by animeshjain9** [comment]
Hi Rishi,

I have put the experiments folder under the Story folder. Please let me know if you won't find them.

Regards,
Animesh Jain

**Comment by rishi11** [comment]
Ok.

**Comment by rishi11** [comment]
This will not be counted as issue. Sorry for inconvenience caused.
